# Generated by Django 4.1 on 2026-01-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                ("parking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount_of_spots", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "parking",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "parking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parking.parking",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking",
            },
        ),
    ]
