# Generated by Django 4.1 on 2026-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                auto_created=True, default=2, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
