# Generated by Django 4.1 on 2026-02-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_remove_user_user_id_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
