# Generated by Django 4.1 on 2026-02-09 16:01

from django.db import migrations, models
import django.utils.timezone


def populate_user_ids(apps, schema_editor):
    """Populate user_id for existing users"""
    User = apps.get_model('parking', 'User')
    for index, user in enumerate(User.objects.all(), start=1):
        user.user_id = index
        user.save(update_fields=['user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0004_alter_user_id"),
    ]

    operations = [
        # First, add user_id as nullable field
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(null=True, blank=True),
        ),
        # Populate user_id for existing users
        migrations.RunPython(populate_user_ids, migrations.RunPython.noop),
        # Now make it non-nullable
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(unique=True),
        ),
        # Remove old id field
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        # Make user_id the primary key
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        # Add other fields
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
