# Generated by Django 4.1 on 2026-02-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0006_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
